### ISSUE TITLE
Button to add differentially expressed genes, so they can be used by VIP

### ISSUE THREAD

**Issue by haessar** [iii-cell-atlas/cellxgene_VIP#4]
Currently when selecting two groups of cells and running differential expression, the genes appear in the right-hand panel, but still need to be manually added  via the "Add Genes" field to allow their use in VIP interface. This behaviour was flagged by Kathryn Crouch.

I note that cellxgene_VIP uses an older cellxgene version (0.16.8), while newer versions of cellxgene (>1.0) allow the creation of "gene sets" when performing DE. However, as per this issue (Jan '22) https://github.com/interactivereport/cellxgene_VIP/issues/62 the developers are not inclined to upgrade due to the removal of the --dataroot option in newer cellxgene versions.

I propose that we add a simple button next to each gene revealed by DE to add it to the set of "selected" genes for use in VIP. We can also explore updating our version of cellxgene to see how well gene sets can be adapted to VIP.

**Comment by haessar** [comment]
![image](https://user-images.githubusercontent.com/11962461/161724277-77f21444-986e-433e-bf48-57116e061b24.png)

**Comment by EdwardAgboraw** [comment]
I've added an "Add DEG Genes as Set" button to the "Add Genes" Tab. It basically just checks if there are any DEG Gene histograms in the right-hand panel and, if there is, extracts the gene names and loads them all as a set titled "DEG Genes". If there are no histograms present than it returns the following error message: "Error - no preloaded DEG genes present. "

**Comment by EdwardAgboraw** [comment]
![cxgpic](https://user-images.githubusercontent.com/18103832/165979649-29a698a4-8b9c-4c6b-9151-2164e7de4145.PNG)
